### ISSUE TITLE
关于对比实验部分

### ISSUE THREAD

**Issue by another1s** [liushulinle/CRASpell#3]
有两个小问题：

- 为啥只放了token-wise的detection 和correction的结果
- 为啥SpellGCN在sighan2015的数据和CRAspell论文中不一样？同样的问题也出现在plome上面，CRAspell中的效果也比原论文差了好几个点，但plome又与SpellGCN原文的数据是一致的
![a79726bfc5482411c75a21a48f7c657](https://user-images.githubusercontent.com/21125331/187865463-cf1c80db-4846-4a32-b8f8-e5fa0a7bdb5d.png)

**Comment by liushulinle** [comment]
SpellGCN指标和原论文不一致是因为评估方式不同，在Plome论文中，表2和表3分别展示了不同评估方式下SpellGCN的指标。具体的评估区别以及为什么要采用不同的评估方法在Plome论文4.4节有介绍，可以参考

**Comment by liushulinle** [comment]
SpellGCN的评估方式和实际情况有一定的gap，指标会偏高。CRAC spell论文没有采用原始SpellGCN的评估方法，中采用了Plome表3的评估方法，因此SpellGCN的指标和原论文不一致

**Comment by another1s** [comment]
> 
多谢回复
返回去读了一下有点麻。。。。。GCNSpell实验里只测了那550句positive sentence的正确率么。。。。那为啥correction F1会保持不变呢，有点没想明白

**Comment by liushulinle** [comment]
这个是巧合吧，可以看到P和R都不同，F相同

**Comment by liushulinle** [comment]
纠正的指标是在检测正确的子集里计算的，这部分差异不大

**Comment by another1s** [comment]
> 纠正的指标是在检测正确的子集里计算的，这部分差异不大

修正过后的检测是在全量数据上检的，但多了500句negative的句子以后，纠正的f1差不多，那岂不是基本可以认为在500句negative上模型的校正效果基本与单在500句positive大体差不多。
但detection效果相比未修正前却下滑了不少。。。我脑子有点转不过来了

**Comment by liushulinle** [comment]
纠正的评估是在检测正确的结果上进行评估的，因此从新增的negative中误检测的结果，不会进入到纠正的评估中

**Comment by another1s** [comment]
> 纠正的评估是在检测正确的结果上进行评估的，因此从新增的negative中误检测的结果，不会进入到纠正的评估中

好吧好吧原来是这样。我明白了。多谢解答
